export const SHOW_EDIT_TASK_POPUP = 'SHOW_EDIT_TASK_POPUP';
export const CLOSE_EDIT_TASK_POPUP = 'CLOSE_EDIT_TASK_POPUP';
export const SHOW_DELETE_TASK_POPUP = 'SHOW_DELETE_TASK_POPUP';
export const CLOSE_DELETE_TASK_POPUP = 'CLOSE_DELETE_TASK_POPUP';
export const SHOW_DELETE_ALL_TASKS_POPUP = 'SHOW_DELETE_ALL_TASKS_POPUP';
export const CLOSE_DELETE_ALL_TASKS_POPUP = 'CLOSE_DELETE_ALL_TASKS_POPUP';